[theme]
# Quiet Light inspired theme
base = "light" # Ensure we start from a light base

primaryColor="#6eb52f" # A muted green accent
backgroundColor="#f0f0f5" # Off-white/very light grey main background
secondaryBackgroundColor="#e0e0ef" # Slightly darker grey for sidebar/widgets
textColor="#262730" # Dark grey text
font="sans serif" # Standard sans serif font
